# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-02-04 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_from', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_to', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_response', models.CharField(blank=True, max_length=255, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_message',
                'managed': False,
            },
        ),
    ]
