# Generated by Django 5.1.7 on 2025-05-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage353',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_from', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_to', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sms_response', models.CharField(blank=True, max_length=600, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Мессежээр дугаар хайх',
                'verbose_name_plural': 'Мессежээр дугаар хайх жагсаалт',
                'db_table': 'user_message_353',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
